### PR TITLE
Kubernetes docs fixes

### PR DESCRIPTION
**Pull request by edevil**
Corrected command line parameter.
Increased number of replicas, otherwise with one replica and
a PDB min avail 1 the pod could not be moved. Also, increases
availability of service.
Corrected labels so that they match with label selector.

### CODE REVIEW

**Comment by GMartinez-Sisti** [comment]
Hi @edevil, 

Thank you for contributing!

LGTM.

**Comment by edevil** [comment]
@GMartinez-Sisti I've reached a point where the envoy proxy keeps getting restarted since it is not listening at the specified port for the k8s healthchecks. In fact, it isn't listening on any port besides localhost:9901, which obviously cannot be used for external health checks. I've also tried disabling the health-checks so the pod stays up, but I see no interaction between envoy and the proxy client in the logs. In addition, the web dashboard shows no activity for this access proxy.

**Comment by pablosole** [comment]
Hi @edevil, please make sure you have at least one resource added into the proxy, it won't open the listener if the proxy is completely empty. We plan to address this soon to make it easier to test the deployment though.

**Comment by edevil** [comment]
@pablosole I do not have any configured resource, I was following the documentation for the proxy install and it did not mention resources.

Regarding the proxy, the host and port are supposed to be publicly accessible? Because the kubernetes manifests do not create a load balancer service or an ingress rule for that.

Regarding the resource, what is the "public host" and "resource host"? Does the resource have be exposed to the public?

**Comment by pablosole** [comment]
@edevil The proxy needs to have its host and port accessible publicly, it is what your users will use to access the internal resources.

The resources are configured through the management console (Access section -> Resources -> +) and they have a private leg and a public one. The private leg, also called Resource Host in the configuration, is the internal host or IP address of the resource you intend to expose through the proxy.

The Public Host is the domain name your users will refer to when accessing this resource. This domain name doesn't need to be registered in a real DNS server since our traffic interception client will handle the domain resolution for you, it is simply a marker that we will use to determine a new secure transport connection needs to be initiated.

For example, you could have an SSH server listening in an internal Linux box at `10.1.1.1` and call that `srv01.internal.local`. Then any user enrolled in your tenant with the right to access it will simply do something like `ssh srv01.internal.local` and our system will create a transparent secure tunnel around the connection and patch it through the proxy and into the `10.1.1.1` host.

**Comment by edevil** [comment]
@pablosole I've since added 2 resources, and I see references to them in the envoy [config](https://pastebin.com/PASTtRQG). However, I cannot connect to them. I've tried inside the pod itself:

```
[root@envoy-proxy-8d568b874-wvfsx /]# netstat -an |grep -i listen
tcp        0      0 0.0.0.0:9000            0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:9901          0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN
[root@envoy-proxy-8d568b874-wvfsx /]# curl http://localhost:8000
curl: (56) Recv failure: Connection reset by peer
```

I've also installed the iOS app, how do I connect the iOS app to this enterprise account?

**Comment by GMartinez-Sisti** [comment]
Hi @edevil,

To connect to a resource through envoy you need to be authenticated and authorised, this will happen transparently when the Fyde Client is running on the device you are performing the request.

To enrol a device please [add a user](https://github.com/fydeinc/docs/blob/master/console/configurations/add_user.md) to the console, if you specify an email address the enrol steps will be sent. If you didn't add an email, or want to resend it, please check the instructions [here](https://github.com/fydeinc/docs/blob/master/console/configurations/resend_enrollment_email.md).

Let me know if you need more information, if you want we can continue this talk offline.

**Comment by edevil** [comment]
@GMartinez-Sisti I added a new user, but the e-mail only mentions the macos app:

Screen Shot 2019-04-17 at 13 17 02

How do I enroll the ios app?

**Comment by GMartinez-Sisti** [comment]
@edevil The enrolment link needs to be opened from the device that will enrol. Please open the link from the iOS device and the webpage will adjust accordingly.

**Comment by edevil** [comment]
@GMartinez-Sisti Ok, so I've enrolled an iOS app. I have two resources with public hosts "metrics.brpx" and "noder.brpx". They have an access policy of "Allow everyone". I've tried to enter these addresses on the chrome url bar but I get directed to a google search, it seems the vpn client was not able to intercept these requests. Am I doing this wrong?

**Comment by GMartinez-Sisti** [comment]
@edevil We've seen this behaviour before with chrome. By default, modern browsers try to search from the address bar if they are not able to recognise the content as a valid URL, when using custom domains this behaviour is usually triggered.

Please try it again by specifying the desired protocol. Example: `http://metrics.brpx` or `https://metrics.brpx`.

**Comment by edevil** [comment]
@GMartinez-Sisti I've managed to get it to work. Thanks for your help!

**Comment by GMartinez-Sisti** [comment]
@edevil That's great! Thanks for the feedback.

We're going to check this iteration and improve our documentation based on these pain points.

Regards

**Pull request merged**
